baseURL: https://vlkozl.github.io
languageCode: en-us
title: Vladimir Kozlov Tech.Journal
copyright: Vladimir Kozlov Tech.Journal (c) 2023
paginate: 6
theme: PaperMod

# enableInlineShortcodes: true
googleAnalytics: G-D50SJWV844
enableEmoji: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
