baseURL: https://vlkozl.github.io/journal/
languageCode: en-us
title: Vladimir Kozlov Tech.Journal
copyright: Vladimir Kozlov Tech.Journal (c) 2023
paginate: 6
theme: github.com/adityatelange/hugo-PaperMod
