main:
  - identifier: archives
    name: Archives
    url: /archives/
    weight: 50
  # - identifier: categories
  #   name: Categories
  #   url: /categories/
  #   weight: 60
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 70
  - identifier: search
    name: Search
    url: search/
    weight: 80
  - identifier: about
    name: About
    url: /about/
    weight: 40
